spring:
  application:
    name: order-service

  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password: password
    url: jdbc:mysql://localhost:3306/epic_figures_order
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li5fRSLhcmlB7nDs
            client-secret: 729963bd07baffdc0830c6a8afdbc2434ccc2892
            # scope: email, public_profile
          google:
#            client-id: 1086239543051-slijoqf2pnhskd4q2d4qg89uuod0p8cl.apps.googleusercontent.com
#            client-secret: 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
            client-id: 1086239543051-ug33jsc1pdhsaai2kna5gk69kutdd1re.apps.googleusercontent.com
            client-secret: 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

          facebook:
            client-id: 1632890864218116
            client-secret: 80be9bb154d02c8fc043624aab30c788
server:
  port: 8084

# only log the SQL statements
logging:
  level:
    org.springframework.security: DEBUG

    org.hibernate.SQL: TRACE
    org.hibernate.orm.jdbc.bind: TRACE

bezkoder:
  openapi:
    dev-url: http://localhost:8081

application:
  jwtExpirationMs: 86400000
  returnUrl: http://localhost:4200

cloudinary:
  cloud-name: dptyuisjr
  api-key: 119697286713644
  api-secret: H_SMqmlh1dz6G8FXx9sla0dt8OI

file:
  upload-logo-dir: ./uploads/logo
  upload-product-image-dir: ./uploads/productimage
  upload-user-image-dir: ./uploads/userimage
  upload-thumbnail-image-dir: ./uploads/thumbnailimage

